# Generated by Django 6.0.3 on 2026-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_educationalplan_direction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalplan',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл плана'),
        ),
    ]
