# Generated by Django 6.0.3 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_alter_educationalplan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalplan",
            name="source_path",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                unique=True,
                verbose_name="Путь к исходному файлу (относительно userfiles)",
            ),
        ),
    ]

