# Generated by Django 6.0.3 on 2026-04-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_educationalplan_source_path_and_file_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationalplan",
            name="file",
        ),
    ]

