# Generated by Django 6.0.4 on 2026-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_educationalplan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
