# Generated by Django 6.0.4 on 2026-07-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_educationalplan_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalPlan',
        ),
    ]
