# Generated by Django 6.0.4 on 2026-06-25 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждения',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('plx', 'Учебный план (PLX)'), ('generic', 'Общий документ')], db_index=True, max_length=80, verbose_name='Тип')),
                ('canonical_name', models.CharField(db_index=True, max_length=255, verbose_name='Каноническое имя')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Пояснение')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=80, unique=True, verbose_name='Тип документа')),
                ('naming_strategy_key', models.CharField(max_length=120, verbose_name='Стратегия именования')),
                ('rename_policy_key', models.CharField(blank=True, default='', max_length=120)),
                ('metadata_extractor_key', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Стратегия типа документа',
                'verbose_name_plural': 'Стратегии типов документов',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.IntegerField(blank=True, null=True, verbose_name='Автор')),
                ('after_message_id', models.UUIDField(blank=True, null=True)),
                ('replies_to_message_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.discussionthread', verbose_name='Тред')),
            ],
            options={
                'verbose_name': 'Сообщение обсуждения',
                'verbose_name_plural': 'Сообщения обсуждения',
            },
        ),
        migrations.CreateModel(
            name='DocumentAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Алиас')),
                ('alias_source', models.CharField(blank=True, default='', max_length=64, verbose_name='Источник алиаса')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='documents.document')),
            ],
            options={
                'verbose_name': 'Алиас документа',
                'verbose_name_plural': 'Алиасы документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('on_review', 'На проверке'), ('needs_fix', 'Требует доработки'), ('approved', 'Утверждён'), ('archived', 'В архиве'), ('invalid', 'Невалидный'), ('trashed', 'В корзине')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('source_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('storage_key', models.CharField(max_length=500, verbose_name='Ключ хранения')),
                ('content_hash', models.CharField(db_index=True, max_length=128, verbose_name='Хэш содержимого')),
                ('created_by_user_id', models.IntegerField(blank=True, null=True, verbose_name='Автор')),
                ('change_comment', models.TextField(blank=True, default='', verbose_name='Комментарий к версии')),
                ('extracted_metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('error_messages', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='Текущая версия'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='document_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_thread', to='documents.documentversion', verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=32, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=32, verbose_name='В статус')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('action_comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('actor_id', models.IntegerField(blank=True, null=True, verbose_name='Исполнитель')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Переход workflow',
                'verbose_name_plural': 'Переходы workflow',
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
    ]
