# Generated by Django 6.0.3 on 2026-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='plans/', verbose_name='Файл плана')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('department', models.CharField(max_length=100, verbose_name='Кафедра')),
                ('direction', models.CharField(max_length=200, verbose_name='Направление подготовки')),
                ('year_start', models.IntegerField(verbose_name='Год начала подготовки')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Утверждён'), ('rejected', 'Отправлен на доработку')], default='draft', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
    ]
