# Generated by Django 6.0.3 on 2026-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalplan',
            name='direction_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код направления'),
        ),
        migrations.AddField(
            model_name='educationalplan',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='educationalplan',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='educationalplan',
            name='direction',
            field=models.CharField(blank=True, max_length=300, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='educationalplan',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='educationalplan',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала подготовки'),
        ),
    ]
