# Generated by Django 6.0.4 on 2026-08-22 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_approved_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('provider_key', models.CharField(default='yandex_disk', max_length=64, verbose_name='Провайдер')),
                ('root_path', models.CharField(default='/', max_length=500, verbose_name='Корневой путь')),
                ('credential_ref', models.CharField(max_length=128, verbose_name='Ссылка на секрет')),
                ('write_mode', models.CharField(choices=[('read_only', 'Только чтение'), ('read_write', 'Чтение и запись')], default='read_write', max_length=16, verbose_name='Режим доступа')),
                ('enabled', models.BooleanField(default=True, verbose_name='Подключение включено')),
                ('pull_enabled', models.BooleanField(default=False, verbose_name='Получать изменения')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Отправлять утверждённые версии')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='Запускать по расписанию')),
                ('manual_run_enabled', models.BooleanField(default=True, verbose_name='Разрешить ручной запуск')),
                ('on_active_missing', models.CharField(choices=[('archive_local', 'Архивировать локально'), ('keep_and_report', 'Сохранить и сообщить')], default='archive_local', max_length=32, verbose_name='Если актуальный файл исчез на диске')),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний checkpoint')),
                ('lease_token', models.CharField(blank=True, default='', max_length=64, verbose_name='Lease')),
                ('lease_until', models.DateTimeField(blank=True, null=True, verbose_name='Lease до')),
            ],
            options={
                'verbose_name': 'Внешнее подключение',
                'verbose_name_plural': 'Внешние подключения',
            },
        ),
        migrations.CreateModel(
            name='ExternalSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sync_enabled', models.BooleanField(default=False, verbose_name='Внешняя синхронизация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки внешней синхронизации',
                'verbose_name_plural': 'Настройки внешней синхронизации',
            },
        ),
        migrations.CreateModel(
            name='OutboundIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('publish_active', 'Опубликовать актуальную'), ('move_to_archive', 'Переместить в архив'), ('noop', 'Без действия')], max_length=32, verbose_name='Тип')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ идемпотентности')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paused_by_switch', 'Приостановлено настройкой'), ('in_progress', 'Выполняется'), ('done', 'Выполнено'), ('failed', 'Ошибка')], default='pending', max_length=32, verbose_name='Статус')),
                ('desired_remote_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Целевой путь')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_intents', to='external_sync.externalconnection', verbose_name='Подключение')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_intents', to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Исходящее намерение',
                'verbose_name_plural': 'Исходящие намерения',
            },
        ),
        migrations.CreateModel(
            name='SwitchAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_name', models.CharField(max_length=128, verbose_name='Настройка')),
                ('old_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Было')),
                ('new_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Стало')),
                ('actor_id', models.IntegerField(blank=True, null=True, verbose_name='Исполнитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_audits', to='external_sync.externalconnection', verbose_name='Подключение')),
            ],
            options={
                'verbose_name': 'Аудит переключения',
                'verbose_name_plural': 'Аудит переключений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь на диске')),
                ('summary', models.TextField(verbose_name='Описание')),
                ('resolved', models.BooleanField(default=False, verbose_name='Разрешён')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='external_sync.externalconnection', verbose_name='Подключение')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts', to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Конфликт синхронизации',
                'verbose_name_plural': 'Конфликты синхронизации',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('planning', 'Планирование'), ('applying', 'Применение'), ('completed', 'Завершён'), ('paused', 'Приостановлен'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='Статус')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128, verbose_name='Ключ идемпотентности')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='Импортировано')),
                ('published_count', models.PositiveIntegerField(default=0, verbose_name='Опубликовано')),
                ('archived_count', models.PositiveIntegerField(default=0, verbose_name='Архивировано')),
                ('duplicates_count', models.PositiveIntegerField(default=0, verbose_name='Дубликаты')),
                ('conflicts_count', models.PositiveIntegerField(default=0, verbose_name='Конфликты')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Ошибки')),
                ('report_lines', models.JSONField(blank=True, default=list, verbose_name='Строки отчёта')),
                ('stop_reason', models.TextField(blank=True, default='', verbose_name='Причина остановки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='external_sync.externalconnection', verbose_name='Подключение')),
            ],
            options={
                'verbose_name': 'Прогон синхронизации',
                'verbose_name_plural': 'Прогоны синхронизации',
            },
        ),
        migrations.CreateModel(
            name='ExternalReplica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_path', models.CharField(max_length=500, verbose_name='Путь на диске')),
                ('role', models.CharField(choices=[('active', 'Актуальная'), ('archive', 'Архивная'), ('ignored', 'Игнорируется')], max_length=16, verbose_name='Роль')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная копия')),
                ('sync_state', models.CharField(choices=[('in_sync', 'Синхронизирована'), ('pending_push', 'Ожидает отправки'), ('paused_by_switch', 'Приостановлено настройкой'), ('conflict', 'Расхождение'), ('missing_remote', 'Нет на диске'), ('stale', 'Устарела')], default='in_sync', max_length=32, verbose_name='Состояние согласования')),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее согласование')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='external_sync.externalconnection', verbose_name='Подключение')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_replicas', to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Внешняя копия',
                'verbose_name_plural': 'Внешние копии',
                'constraints': [models.UniqueConstraint(fields=('connection', 'remote_path'), name='uniq_replica_connection_path')],
            },
        ),
        migrations.CreateModel(
            name='RemoteObjectSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_path', models.CharField(max_length=500, verbose_name='Путь на диске')),
                ('remote_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID ресурса')),
                ('role', models.CharField(choices=[('active', 'Актуальная'), ('archive', 'Архивная'), ('ignored', 'Игнорируется')], max_length=16, verbose_name='Роль')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер')),
                ('md5', models.CharField(blank=True, default='', max_length=128, verbose_name='MD5')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменён на диске')),
                ('content_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Хэш содержимого')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='external_sync.externalconnection', verbose_name='Подключение')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_snapshots', to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Слепок удалённого объекта',
                'verbose_name_plural': 'Слепки удалённых объектов',
                'constraints': [models.UniqueConstraint(fields=('connection', 'remote_path'), name='uniq_snapshot_connection_path')],
            },
        ),
    ]
